### ISSUE TITLE
Make it to Github Page

### ISSUE THREAD

**Issue by BransonGitomeh** [BransonGitomeh/ember-university#4]
since our "ember app" the one on github is just one ember app...

si we just hit it up to github pages and itll go live and as we build itll stay live 

then we fire up a aws thing for the sails part

**Comment by BransonGitomeh** [comment]
following @gideon-maina work on salsaUniversity.github.io it's now the official homepage website of this repo live

And we are all very happy :smile_cat:

**Comment by BransonGitomeh** [comment]
now closing

**Comment by gideon-maina** [comment]
definitely
